name: slack-integration

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Slack via Webhook with Attachments
        uses: slackapi/slack-github-action@v2.0.0
        with:
          payload: |
            {
              "text": "A new commit has been pushed!",
              "attachments": [
                {
                  "fallback": "Commit details",
                  "color": "#36a64f",
                  "pretext": "Here are the commit details:",
                  "text": "Commit message: `Test commit message`",
                  "footer": "GitHub",
                  "ts": 123456789
                }
              ]
            }
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
