name: Sitecore goto XDB GOAT Deployment

on:
  push:
    branches: -main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Send a slack notification for the deployment
        id: slack
        uses: slackapi/slack-github-action@v1.27.0
        with:
          # This data can be any valid JSON from a previous step in the GitHub Action
          payload: |
            {
              "channel": "#website",
              "username": "GitHub Actions Bot",
              "icon_url": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
              "text": "Deploy *${{ inputs.release_version }}* to *${{ inputs.environment }}*",
              "attachments": [
                {
                  "fallback": "Deploy following *${{ inputs.release_version }}* to *${{ inputs.environment }}*",
                  "color": "${{ job.status == 'success' && '#36A64F' || '#FF0000' }}",
                  "fields": [
                    {
                      "title": "*Job Status*",
                      "value": "${{ job.status }}\n${{ job.status == 'success' && ':tada:' || ':large_red_circle:' }}",
                      "short": true
                    },
                    {
                      "title": "*Job URL*",
                      "value": "<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Click here for details>",
                      "short": true
                    },
                    {
                      "title": "*Branch*",
                      "value": "${{ github.ref }}",
                      "short": true
                    },
                    {
                      "title": "*Deployed by*",
                      "value": "${{ github.actor }}",
                      "short": true
                    },
                    {
                      "title": "*Webapp Name*",
                      "value": "${{ matrix.AZURE_Details.webapp_name }}",
                      "short": true
                    },
                    {
                      "title": "*Webapp URL*",
                      "value": "<https://${{ matrix.AZURE_Details.webapp_name }}.azurewebsites.net|${{ matrix.AZURE_Details.webapp_name }}.azurewebsites.net>",
                      "short": true
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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
